excluded:
    - Pods
    - Libraries
    - StudyMatching/StudyMatchingTests
    - StudyMatching/StudyMatchingUITests
included:
    
disabled_rules:
    - leading_whitespace
    - trailing_whitespace
    - multiple_closures_with_trailing_closure
    - identifier_name
    
line_length:
  ignores_comments: true

nesting:
  type_level:
    warning: 5
    error: 6
  function_level:
    warning: 5
    error: 10

cyclomatic_complexity:
  warning: 18
  error: 20
