# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'StudyMatching' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyMatching
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
  pod 'SnapKit', '~> 5.6.0'
  pod 'SwiftLint'
  pod 'Swinject'
  
end
